// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: salt.proto

package puzzlesaltservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SaltClient is the client API for Salt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaltClient interface {
	LoadOrGenerate(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type saltClient struct {
	cc grpc.ClientConnInterface
}

func NewSaltClient(cc grpc.ClientConnInterface) SaltClient {
	return &saltClient{cc}
}

func (c *saltClient) LoadOrGenerate(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/puzzlesaltservice.Salt/LoadOrGenerate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaltServer is the server API for Salt service.
// All implementations must embed UnimplementedSaltServer
// for forward compatibility
type SaltServer interface {
	LoadOrGenerate(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedSaltServer()
}

// UnimplementedSaltServer must be embedded to have forward compatible implementations.
type UnimplementedSaltServer struct {
}

func (UnimplementedSaltServer) LoadOrGenerate(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadOrGenerate not implemented")
}
func (UnimplementedSaltServer) mustEmbedUnimplementedSaltServer() {}

// UnsafeSaltServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaltServer will
// result in compilation errors.
type UnsafeSaltServer interface {
	mustEmbedUnimplementedSaltServer()
}

func RegisterSaltServer(s grpc.ServiceRegistrar, srv SaltServer) {
	s.RegisterService(&Salt_ServiceDesc, srv)
}

func _Salt_LoadOrGenerate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaltServer).LoadOrGenerate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/puzzlesaltservice.Salt/LoadOrGenerate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaltServer).LoadOrGenerate(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Salt_ServiceDesc is the grpc.ServiceDesc for Salt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Salt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "puzzlesaltservice.Salt",
	HandlerType: (*SaltServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadOrGenerate",
			Handler:    _Salt_LoadOrGenerate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "salt.proto",
}
